initial import of pre-git release: viros-0.6.2009_12_21
The viros-0.6.2009_12_21 release predates the sourceforge git tree.
It was originally publically hosted at filteredperception.org.

diff --git a/tools/scripts/functions b/tools/scripts/functions
--- a/tools/scripts/functions
+++ b/tools/scripts/functions
@@ -6,16 +6,15 @@
 #
 #############################################################################
 #
-# Copyright 2007 Douglas McClendon <dmc AT filteredperception DOT org>
+# Copyright 2007-2009 Douglas McClendon <dmc AT filteredperception DOT org>
 #
 #############################################################################
 #
-#This file is part of VirOS.
+# This file is part of VirOS.
 #
 #    VirOS is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
+#    the Free Software Foundation, version 3 of the License.
 #
 #    VirOS is distributed in the hope that it will be useful,
 #    but WITHOUT ANY WARRANTY; without even the implied warranty of
@@ -27,7 +26,15 @@
 #
 #############################################################################
 
+##
+## VirOS funcions
+##
+## utility functions for viros scripts
+##
 
+##
+## set default values for undefined globals that are used
+##
 if [ "x${viros_comtrace}" == "x" ]; then
     viros_comtrace="VirOS-${progname}"
 fi
@@ -56,6 +63,14 @@ if [ "x${cleanup_command}" == "x" ]; then
     cleanup_command="echo cleaning up..."
 fi
 
+#
+# usage: normalize_path <path>
+#
+# normalize_path will take a path to a file or directory, and return
+# an equivalent non-relative (non-symlink?) path
+#
+# globals used: none
+#
 function normalize_path {
     result=$( cd $( dirname $1 ) ; pwd )/$( basename $1 )
     if (($?)); then
@@ -66,8 +81,18 @@ function normalize_path {
 }
 
 
+#
+# usage: veva command args...
+#
+# the vsys eval wrapper runs a command, redirecting it's output to 
+# a nicely formatted log entry
+#
+# globals used: progname, logfiles
+#
 function veva {
 
+    # in debug mode, send debug messages to stdout as well as logfiles
+    # (doesn't seem to work tho)
     if (($vopt_debug)); then
 	vlogfiles="${logfiles} /dev/stdout"
     else
@@ -81,6 +106,8 @@ function veva {
 	echo "${progname}: status: $@" >> $logfile
     done
 
+    # I have not yet verified that pipefail is doing what I think its doing
+    # (my first ever use of pipefail)
     set -o pipefail
     if (($vopt_debug)); then
 	eval $@ 2>&1 | tee -a $logfiles
@@ -100,8 +127,12 @@ function veva {
     return $retval
 }
 
+# stupid workaround for my lack of level 99 bash gurudom
+# (no doubt I'll find a better method than this at some point)
 function vevastupid {
 
+    # in debug mode, send debug messages to stdout as well as logfiles
+    # (doesn't seem to work tho)
     if (($vopt_debug)); then
 	vlogfiles="${logfiles} /dev/stdout"
     else
@@ -118,10 +149,13 @@ function vevastupid {
     for (( i=1 ; $i <= $# ; i=$(( $i + 1 )) )); do
 	eval "datcopy[$i]=\$$i"
 	if ( echo "${datcopy[$i]}" | grep -q "___" ); then
+#	    datcopy[$i]="\"$( echo ${datcopy[$i]} | sed -e 's/VirOS_Synthesis_Monitor/VirOS\ Synthesis\ Monitor/')\""
 	    datcopy[$i]="\"$( echo ${datcopy[$i]} | sed -e 's/___/\ /g' )\""
 	fi
     done
 
+    # I have not yet verified that pipefail is doing what I think its doing
+    # (my first ever use of pipefail)
     set -o pipefail
     if (($vopt_debug)); then
 	eval ${datcopy[@]} 2>&1 | tee -a $logfiles
@@ -141,6 +175,14 @@ function vevastupid {
     return $retval
 }
 
+#
+# usage: die <message...>
+#
+# Generic error condition exit function used as a last resort when a more
+# graceful handling of the error is not possible or not yet implemented.
+#
+# globals used: cleanup_command
+#
 function die {
     echo -en "\n"
     status "===================================="
@@ -150,6 +192,9 @@ function die {
     status "VSYS has exited prior to task completion"
     status "===================================="
 
+    ##
+    ## clean up
+    ##
     status "cleaning up..."
     status "(please wait up to 1 minute if possible)"
     if (($vopt_debug)); then
@@ -161,6 +206,17 @@ function die {
     exit 1
 }
 
+#
+# usage: die_bug <message...>
+#
+# Generic error condition exit function used as a last resort when a more
+# graceful handling of the error is not possible or not yet implemented.
+#
+# the _bug version of die is called when a truly unexpected condition 
+# warrants developer feedback 
+#
+# globals used: cleanup_command
+#
 function die_bug {
     status "===================================="
     status $@
@@ -171,12 +227,22 @@ function die_bug {
     status "please submit a bug report to bugs@viros.org"
     status "===================================="
 
+    ##
+    ## clean up
+    ##
     status "cleaning up..."
     veva $cleanup_command
 
     exit 1
 }
 
+#
+# usage: debug <message...>
+#
+# wrapper for sending status messages to console and log
+#
+# globals used: progname, logfiles(not required)
+#
 function debug {
     time="$( date +%Y-%m-%d:%H:%M:%S )"
     if (($vopt_debug)); then
@@ -187,6 +253,13 @@ function debug {
     done
 }
 
+#
+# usage: debugcat <filename>
+#
+# wrapper for sending status messages to console and log
+#
+# globals used: progname, logfiles(not required)
+#
 function debugcat {
     if [ ! -f $1 ]; then
 	die "file $1 can not be debugcat-ed"
@@ -203,6 +276,13 @@ function debugcat {
     done
 }
 
+#
+# usage: verbose <message...>
+#
+# wrapper for sending status messages to console and log
+#
+# globals used: progname, logfiles(not required)
+#
 function verbose {
     time="$( date +%Y-%m-%d:%H:%M:%S )"
     if (($vopt_verbose)); then
@@ -211,12 +291,21 @@ function verbose {
 	echo "${viros_comtrace}: ${time}: verbose: $@"
     fi
     for logfile in $logfiles; do
+	# todo: figure out why this if case is necessary
+	# (triggerred a failure when I did a ctrl c on a non --debug run)
 	if [ -d "$( dirname $logfile )" ]; then
 	    echo "${progname}: ${time}: verbose: $@" >> $logfile
 	fi
     done
 }
 
+#
+# usage: status <message...>
+#
+# wrapper for sending status messages to console and log
+#
+# globals used: progname, logfiles(not required)
+#
 function status {
     bequiet=0
     if [ "x${vopt_quiet}" == "x1" ]; then
@@ -234,6 +323,12 @@ function status {
     done
 }
 
+#
+# usage: simple_statuslogger <logfile>
+#
+# this function passes it's stdin to the logfile, and outputs a . to stdout
+# for every line of stdin.
+#
 function simple_statuslogger {
     wdone=0
     while (( !$wdone )); do
@@ -250,6 +345,14 @@ function simple_statuslogger {
     echo -en "\n"
 }
 
+#
+# usage: statuslogger <logfile>
+#
+# like statuslogger, but designed for the os installer output
+# (anaconda.log and other).  In addition, lines of dots are broken either
+# when they hit $numdots_perline, or when a timestamp has not been printed
+# in more than $minvalsecs
+#
 function statuslogger {
     logfile=$1
     msg_prefix=$2
@@ -277,6 +380,9 @@ function statuslogger {
         read
 	wdone=$?
 
+	# todo: use a timer, and if the time since the 
+	# last divcount reset has been longer than a constant
+	# go ahead and jump divcount to divider
 	divcount=$(( $divcount + 1 ))
 
 	if [ $divcount -eq $divider ]; then
@@ -306,6 +412,15 @@ function statuslogger {
     echo -en "\n"
 }
 
+#
+# usage: waitonoutput <filename> <string> <period> <timeout>
+#
+# waitonoutput watches a particular filename, looking for the given
+# string.  waitonouput will check periodically with the period 
+# specified in seconds, until a maximum timeout value specified in
+# seconds.  If the string is found before the timeout expires, 0 (no error)
+# is returned.  Otherwise, 1 (error) will be returned
+#
 function waitonoutput {
     
     filename="$1"
@@ -313,6 +428,7 @@ function waitonoutput {
     period="$3"
     timeout="$4"
 
+    # local variables
     timeelapsed=0
     
     while [ true ]; do
@@ -329,13 +445,52 @@ function waitonoutput {
     done
 }
 
+##
+## usage: make_vncstartup <output_twmrc_filename>
+##
+## generates a minimal xstartup for Xvnc suitable for qemu in qrap
+##
 function make_vncstartup {
     cat <<EOF > $1
+#!/bin/bash
+#twm &
+#xterm &
 EOF
     chmod +x $1
 }
 
+function install_smirfgen {
+    src_dir=${1}
+    dest_dir=${2}
+
+    verbose "installing smirfgen..."
+    mkdir ${dest_dir}/lib/viros
+    mkdir ${dest_dir}/lib/viros/scripts
+    mkdir ${dest_dir}/lib/viros/ZyX-Live-OS
+    cp ${src_dir}/bin/smirfgen \
+	${dest_dir}/bin/smirfgen
+    # XXX: expediency, splitter should probably be bashified someday
+    if [ -x /bin/splitter ]; then
+	cp /bin/splitter \
+	    ${dest_dir}/bin/splitter
+    elif [ -x /usr/bin/splitter ]; then
+	cp /usr/bin/splitter \
+	    ${dest_dir}/bin/splitter
+    else
+	die "no splitter available"
+    fi
+    
+    cp -av ${src_dir}/lib/viros/scripts/* \
+	${dest_dir}/lib/viros/scripts/
+    cp -av ${src_dir}/lib/viros/ZyX-Live-OS/* \
+	${dest_dir}/lib/viros/ZyX-Live-OS/
+}
+
+
 function cleanup_and_exit {
+    ##
+    ## cleanup and exit
+    ##
     if (( $vopt_debug )); then
 	verbose "debug enabled: NOT removing tmpdir ${tmpdir}"
     else
diff --git a/tools/scripts/qfakeroot b/tools/scripts/qfakeroot
--- a/tools/scripts/qfakeroot
+++ b/tools/scripts/qfakeroot
@@ -6,16 +6,15 @@
 #
 #############################################################################
 #
-# Copyright 2007 Douglas McClendon <dmc AT filteredperception DOT org>
+# Copyright 2007-2009 Douglas McClendon <dmc AT filteredperception DOT org>
 #
 #############################################################################
 #
-#This file is part of VirOS.
+# This file is part of VirOS.
 #
 #    VirOS is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
+#    the Free Software Foundation, version 3 of the License.
 #
 #    VirOS is distributed in the hope that it will be useful,
 #    but WITHOUT ANY WARRANTY; without even the implied warranty of
@@ -27,8 +26,14 @@
 #
 #############################################################################
 
+##
+## constant definitions
+##
 viros_prefix=/usr
 
+##
+## load viros system library
+##
 if [ -f "$( dirname $0 )/libvsys.sh" ]; then
     source "$( dirname $0 )/libvsys.sh"
 elif [ -f "${viros_prefix}/lib/viros/scripts/libvsys.sh" ]; then 
@@ -38,6 +43,9 @@ else
     exit 1
 fi
 
+##
+## override libvopt.sh usage function
+##
 function usage {
     echo ""
     echo "qfakeroot \\"
@@ -47,7 +55,9 @@ function usage {
     echo "    [--native] \\"
     echo "    [--config=<config-file>] \\"
     echo "    [--command=<program-to-run-as-root>] \\"
-    echo "    [[--disk_image=[ro:]<disk-image-device-or-file>]] \\"
+    echo "    [--disk_image=[ro:]<disk-image-device-or-file>] \\"
+    echo "    [--guest_smirf] \\"
+    echo "    [[--add_nonvsi_files=<file-list>]] \\"
     echo "    [[--add_files=<file-list>]] \\"
     echo "    [[--add_links=<link-list>]] \\"
     echo "    [[--add_modules=<module-list>]] \\"
@@ -63,13 +73,22 @@ function usage {
     fi
 }
 
+##
+## globals
+##
 if [ "$( whoami )" == "root" ]; then
     native_default=1
 else
     native_default=0
 fi
 
+##
+## functions
+##
 
+##
+## use TMPDIR environment if set
+##
 
 if [ "x${TMPDIR}" == "x1" ]; then
     default_vopt_tmpdir="/tmp"
@@ -78,18 +97,25 @@ else
 fi
 
 
+##
+## define and parse options
+##
 vregopt help boolean 0
 vregopt verbose boolean 0 inherit
 vregopt debug boolean 0 inherit
 vregopt quiet boolean 0 inherit
 vregopt tmpdir string "${default_vopt_tmpdir}" inherit
 vregopt native boolean $native_default
+# experiment, was having tar zyx-live.iso 1024 of 10240 blabla...
+#vregopt scratch string "10G"
 vregopt scratch string "24G"
 vregopt qflags string ""
 vregopt config string ""
 vregopt command string ""
 vregopt disk_image string ""
+vregopt guest_smirf boolean 0
 vregopt add_files cumulative ""
+vregopt add_nonvsi_files cumulative ""
 vregopt add_links cumulative ""
 vregopt add_modules cumulative ""
 vregopt add_module_groups cumulative ""
@@ -115,6 +141,12 @@ fi
 export TMPDIR=${tmpdir}
 verbose "temporary directory is ${tmpdir}"
 
+##
+## handle disk_image initialization
+##
+## note: qcow2 base image is an extra layer of protection for readonly, as
+##       dm-parts should also provide adequate protection.
+##
 if [ "x${vopt_disk_image}" == "x" ]; then
     use_disk_image=0
     qemu-img create ${tmpdir}/fqdi.img 1G
@@ -138,6 +170,12 @@ else
 fi
 
 cat <<EOF > ${tmpdir}/qfakeroot.init
+#!/bin/bash
+#
+# qfakeroot.init: having been bootstrapped by the ZyX-LiveOS initramfs init,
+#                 now prepare the qfakeroot environment for the target
+#                 qfakeroot command
+#
 
 PATH="/sbin:/bin:/usr/sbin:/usr/bin"
 
@@ -149,7 +187,9 @@ mknod /dev/initctl p
 modprobe ata_piix
 modprobe sd_mod
 
-udevsettle --timeout=30 || :
+mknod /dev/urandom c 1 9
+
+udevadm settle --timeout=30 || :
 
 cd /
 
@@ -195,6 +235,8 @@ umount /output
 umount /input
 umount /space
 
+# I can't figure out a way to get this to work... back to qreaper
+#halt -f
 echo -en "\n\nqfakeroot.init QEMU_DONE_IN_NEED_OF_SHUTDOWN\n\n"
 sleep 3
 echo -en "\n\nqfakeroot.init QEMU_DONE_IN_NEED_OF_SHUTDOWN\n\n"
@@ -210,6 +252,10 @@ else
     optional_extra_config_string="config ${vopt_config}"
 fi
 
+
+##
+## write smirfgen config
+##
 cat<<SGCEOF > ${tmpdir}/qfakeroot.smirfgen.cfg
 verbose $vopt_verbose
 debug $vopt_debug
@@ -218,19 +264,24 @@ quiet $vopt_quiet
 config ZyX-Live-OS/smirfgen.cfg
 $optional_extra_config_string
 
+
 add_files ${vopt_command}:/sbin/qfakeroot.command:755
 
 add_files ${tmpdir}/qfakeroot.init:/qfakeroot.init:755
+
 add_files ZyX-Live-OS/live.init:/init:755
 add_files scripts/dm-parts:/sbin/:755
+# readlink and sfdisk are for dm-parts
 add_files /sbin/sfdisk
 add_files /usr/bin/readlink
 add_files dir:/input:755
 add_files /sbin/mkfs.ext2
 add_files /sbin/mkfs.ext3
+add_files /sbin/mkfs.ext4
 add_files /bin/date
 add_files /bin/tar
 add_files /bin/sleep
+# I really wish I could get one of the following four to do the right thing
 add_files /sbin/shutdown
 add_files /sbin/reboot
 add_files /sbin/poweroff
@@ -244,6 +295,24 @@ add_tar_dirs /input:input.tar
 add_modules $vopt_add_modules
 add_module_groups $vopt_add_module_groups
 SGCEOF
+
+if (($vopt_guest_smirf)); then
+    host_vsi=$( echo "${vopt_disk_image}" | sed -e 's/^ro://' )
+    cat<<EOF >> ${tmpdir}/qfakeroot.smirfgen.cfg
+quiet 0
+debug 1
+verbose 1
+
+kversion __latest
+host_vsi $host_vsi
+add_nonvsi_files $vopt_add_nonvsi_files
+add_nonvsi_files ${vopt_command}:/sbin/qfakeroot.command:755
+add_nonvsi_files ${tmpdir}/qfakeroot.init:/qfakeroot.init:755
+# TODO: autodetect list of stuffs, or seperate config, or something...
+add_nonvsi_files ZyX-Live-OS/live.init:/init:755
+add_nonvsi_files scripts/dm-parts:/sbin/:755
+EOF
+fi
 
 if (($vopt_debug)); then
     debug "about to dump ${tmpdir}/qfakeroot.smirfgen.cfg"
@@ -262,7 +331,11 @@ smirfgen \
 
 if (($vopt_native)); then
     
+    ##
+    ## run natively as root in a chroot if requested
+    ##
 
+    # build a chroot environment to run the user command
     mkdir ${tmpdir}/nativechroot
     mkdir ${tmpdir}/nativechroot/output
     mkdir ${tmpdir}/nativechroot/scratch
@@ -270,9 +343,11 @@ if (($vopt_native)); then
     tar --sparse -xpsf ${tmpdir}/qfakeroot.initramfs.input.tar
     popd > /dev/null 2>&1
 
+    # expand smirfgen's irfs into the chroot
     zcat ${tmpdir}/qfakeroot.initramfs | \
 	( cd ${tmpdir}/nativechroot ; cpio --extract )
 
+    # bindmount system directories into the chroot
     mkdir -p ${tmpdir}/nativechroot/dev
     mount --bind /dev ${tmpdir}/nativechroot/dev
     mount --bind /dev/pts ${tmpdir}/nativechroot/dev/pts
@@ -286,18 +361,22 @@ if (($vopt_native)); then
     mkdir -p ${tmpdir}/nativechroot/sys
     mount --bind /sys ${tmpdir}/nativechroot/sys
 
+    # set up the disk_image device nodes
     if (( $use_disk_image )); then
 	dm-parts setup $disk_image ${tmpdir}/dm-parts $disk_image_readonly \
 	    ${tmpdir}/nativechroot/dev/qfrdi
     fi
 
+    # do stuff
     /usr/sbin/chroot ${tmpdir}/nativechroot /sbin/qfakeroot.command
 
+    # tear down the disk_image device nodes
     if (( $use_disk_image )); then
 	dm-parts teardown $disk_image ${tmpdir}/dm-parts $disk_image_readonly \
 	    ${tmpdir}/nativechroot/dev/qfrdi
     fi
 
+    # clean up bind mounts
     umount ${tmpdir}/nativechroot/sys
     rmdir ${tmpdir}/nativechroot/sys
 
@@ -311,27 +390,38 @@ if (($vopt_native)); then
     umount ${tmpdir}/nativechroot/dev
     rmdir ${tmpdir}/nativechroot/dev
 
+    # give the user the final output
     mv ${tmpdir}/nativechroot/output ${vopt_outputdir}
 
 else
 
+    ##
+    ## run command in qemu environment
+    ##
 
     veva qemu-img create ${tmpdir}/qscratch ${vopt_scratch}
     veva qemu-img create ${tmpdir}/qoutput 777G
 
+    # pad input to at least traditional blocksize, just in case
     dd if=/dev/zero of=${tmpdir}/qfakeroot.initramfs.input.tar \
 	conv=notrunc oflag=append bs=4k count=1 > /dev/null 2>&1
 
     touch ${tmpdir}/q.log
 
+    # prevent noise to terminal when qreaper time comes
     trap "/bin/true" SIGCHLD
     trap "/bin/true" SIGHUP
 
+    # note, had been using acpi=force, but ran into a spurious divide error crash
+    # (and this may resolve a few other oopses I had encountered historically)
+    # certainly since I'm using the qreaper hack, acpi is meaningless.  Though
+    # hopefully one day I'll solve both the qreaper necessity, and qemu will
+    # provide a working acpi environment.
     qemu \
 	${vopt_qflags} \
 	-boot c \
 	-nographic \
-	-kernel /boot/vmlinuz-$( uname -r ) \
+	-kernel ${tmpdir}/qfakeroot.initramfs.kernel \
 	-initrd ${tmpdir}/qfakeroot.initramfs \
 	-append "debug verbose console=ttyS0 acpi=off drop=early:/qfakeroot.init" \
 	-hdd ${tmpdir}/qscratch \
@@ -345,6 +435,8 @@ else
     trap "kill $qpid ; exit 1" SIGTERM
     trap "kill $qpid ; exit 1" SIGINT
     
+    # annoying workaround to inability to poweroff qemu from initramfs
+    # (there must be a way, I just haven't figured it out... yet)
     if ((${vopt_verbose})); then
 	debug "tailing q.log"
 	tail -f --pid=${qpid} ${tmpdir}/q.log &
@@ -359,6 +451,7 @@ else
 	    debug "killing qemu subprocess again for good measure"
 	    kill -KILL $qpid > /dev/null 2>&1
 	    qdone=1
+	    # restore traps
 	    trap SIGCHLD
 	    trap SIGHUP
 	    trap SIGTERM
@@ -368,6 +461,7 @@ else
 	fi
     done
     
+    # end annoying qreaper workaround
 
     mkdir ${tmpdir}/tmpoutput
     pushd ${tmpdir}/tmpoutput > /dev/null 2>&1
@@ -377,6 +471,7 @@ else
 
     if [ -f ${tmpdir}/fqdi.img ]; then rm -f ${tmpdir}/fqdi.img; fi
     rm -f ${tmpdir}/qscratch
+#    rm -f ${tmpdir}/qfakeroot.initramfs.input.tar
     rm -rf ${tmpdir}/qoutput
 
 fi
