Import of the 2k11.01.09 release used to create and included in Sci-ZyX-0.6.0.3
This release-import includes many bugfixes and enhancements.  Hopefully there
will not be too many more of these mega-patches, and things will stabalize
and see tiny well documented imports/patches going forward.  FWIW, here
are the changelog entries from the specfile-

* Sun Jan 09 2011 Douglas McClendon <dmc.viros@cloudsession.com> - 0.7.2011_01_0
9
- bugfix: qemu not provided by stock el6-x86 repos, so presume it is provided fo
r now
- bugfix: broken and missing documentation in output rpm
- bugfix: update-mirrors.el6 needed an exclude file
- bugfix: strains min/minimal and even platform have correct symlinks
- bugfix: generate was not exporting boot_iso_sha256sum to synthesize
- bugfix: update-mirrors now sans .el6, and exclude file generated on the fly
- tuning: changed qemu mem reqs from 512 to 422, better for my netbook, and seem
s fine
- aesthetic: fixed VNC titlebar sed renaming
- bugfix/workround: live booted rootfs(/) should now be 755 instead of 775(group
:root)
- generate renamed to spawn, zgen to zspawn, more inline with the metaphor
- zgen: fitness/zbuild->scripts/zgen, now with update-mirrors phase by default
- fix add_search_paths and trait_dirs option parsing
- trait for x-zyx: bootsplash-solar
- bugfix: make rpm(&repos) (for non-primary-developers tree)
-  even verified make release from made release is idempotent
- forensic-mode: cheat code to prevent liveos from probing lvm/mdadm
- info/README: added system requirements outline
- update-mirrors: now takes an arg, synth/generate/mutate also utilize good defaults
- check-mirrors: new script for mass checking of rpmsigs

diff --git a/tools/scripts/update-mirrors b/tools/scripts/update-mirrors
--- a/tools/scripts/update-mirrors
+++ b/tools/scripts/update-mirrors
@@ -1,6 +1,44 @@
 #!/bin/bash
 
 ##
+## get runtime environment
+##
+starttime="$( date +%Y%m%d%H%M%S )"
+rundir="$( pwd )"
+progname="$( basename $0 )"
+progdir=$( ( pushd $( dirname $( readlink -e $0 ) ) > /dev/null 2>&1 ; \
+    pwd ; popd > /dev/null 2>&1 ) )
+rundir=$( pwd )
+mypid=$$
+
+
+##
+## get parameter- mirror_root
+##
+
+# default
+mirror_root="${HOME}/.viros/mirrors"
+
+if [ $# -ge 2 ]; then
+    echo "usage: update-mirrors <mirror_root_dir:default-HOME/.viros/mirrors>"
+    exit 1
+elif [ $# -eq 1 ]; then
+    #TODO: this is a lot of hardcoded Crap.  in the name of scizyx0603 release.
+    mirror_root="$( readlink -f ${1} )"
+    rm -f "${HOME}/.viros/mirrors.link"
+    mkdir -p "${HOME}/.viros"
+    ln -s "${mirror_root}" "${HOME}/.viros/mirrors.link"
+fi
+
+if ( ! mkdir -p "${mirror_root}" > /dev/null 2>&1 ); then
+    echo "update-mirrors: error: mirror root - ${mirror_root} - could not be used/made"
+    exit 1
+fi
+
+
+cd "${mirror_root}"
+
+##
 ## in absence of cmdline args, use these for determining type of update
 ##
 
@@ -45,13 +83,24 @@ common_rsync_flags="${common_rsync_flags} -P"
 # live dangerously
 common_rsync_flags="${common_rsync_flags} --delete"
 # ignore some packages (deltarpms, PAE kernel, etc)
-common_rsync_flags="${common_rsync_flags} --exclude-from=exclude"
+# todo: make a libvsys script with proper TMPDIR handling
+common_rsync_flags="${common_rsync_flags} --exclude-from=/tmp/update-mirrors.$$.exclude"
 # use this for bandwidth limiting
 #common_rsync_flags="${common_rsync_flags} --bwlimit=64"
 
 # use this to exclude debug packages
 common_rsync_flags="${common_rsync_flags} --exclude=debug"
 
+# generate exclude file
+cat <<EOF >> /tmp/update-mirrors.$$.exclude
+drpms
+kernel*PAE*
+*kmdl*PAE*
+*kmod*PAE*
+kernel*_8k*
+*kmdl*_8k*
+*kmod*_8k*
+EOF
 
 ####
 #### update sections
@@ -169,6 +218,14 @@ if (($update_el6_atrpms_source)); then
 	rsync://rsync.mirrorservice.org/download.atrpms.net/src/sl6-i386/atrpms/stable/ \
 	el6/atrpms/stable/source/
 fi
+
+# generate viros.mirrors.cfg
+pushd el6 > /dev/null 2>&1
+ls -1A > ./viros.mirrors.cfg
+popd > /dev/null 2>&1
+
+# clean up
+rm -rf /tmp/update-mirrors.$$.exclude
 
 date >> ./last.update.el6
 
